<?php

return [
    'beiqicar_bak' => [
        'driver'        => 'oracle',
        'tns'           => '',
        'host'          => '172.27.15.8',
        'port'          => '1521',
        'database'      => 'mesprd1',
        'username'      => 'beiqicar_bak',
        'password'      => 'beiqicar',
        'charset'       => 'AL32UTF8',
        'prefix'        => '',
        'prefix_schema' => '',
    ],

    'mesprd1' => [
        'driver'        => 'oracle',
        'tns'           => '',
        'host'          => '172.27.15.8',
        'port'          => '1521',
        'database'      => 'mesprd1',
        'username'      => 'beiqicar',
        'password'      => 'beiqicar',
        'charset'       => 'AL32UTF8',
        'prefix'        => '',
        'prefix_schema' => '',
    ],

    'wmsprd1' => [
        'driver'        => 'oracle',
        'tns'           => '',
        'host'          => '172.27.15.8',
        'port'          => '1521',
        'database'      => 'wmsprd1',
        'username'      => 'wmsprd',
        'password'      => 'wmsprd',
        'charset'       => 'AL32UTF8',
        'prefix'        => '',
        'prefix_schema' => '',
    ],

    'wmsprd2' => [
        'driver'        => 'oracle',
        'tns'           => '',
        'host'          => '172.27.15.8',
        'port'          => '1521',
        'database'      => 'wmsprd2',
        'username'      => 'wmsprd',
        'password'      => 'wmsprd',
        'charset'       => 'AL32UTF8',
        'prefix'        => '',
        'prefix_schema' => '',
    ],

    'wmsprd3' => [
        'driver'        => 'oracle',
        'tns'           => '',
        'host'          => '172.27.15.8',
        'port'          => '1521',
        'database'      => 'wmsprd3',
        'username'      => 'wmsprd',
        'password'      => 'wmsprd',
        'charset'       => 'AL32UTF8',
        'prefix'        => '',
        'prefix_schema' => '',
    ],

    'bvbuvfsprt' => [
        'driver'        => 'oracle',
        'tns'           => '',
        'host'          => '172.27.14.2',
        'port'          => '1521',
        'database'      => 'orcl',
        'username'      => 'bvbuvfsprt',
        'password'      => 'hgz123456',
        'charset'       => 'AL32UTF8',
        'prefix'        => '',
        'prefix_schema' => '',
    ],

    'bvbuvfsupd' => [
        'driver'        => 'oracle',
        'tns'           => '',
        'host'          => '10.46.1.24',
        'port'          => '1521',
        'database'      => 'orcl',
        'username'      => 'bvbuvfsupd',
        'password'      => 'hgz123456',
        'charset'       => 'AL32UTF8',
        'prefix'        => '',
        'prefix_schema' => '',
    ],
];
